# Generated by Django 4.0.4 on 2022-04-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=200, null=True, verbose_name='Produto')),
                ('quantidade', models.IntegerField(blank=True, null=True, verbose_name='Quantidade')),
            ],
            options={
                'db_table': 'produtos',
            },
        ),
    ]
